<?php 
define ('constants', TRUE);
include 'tsq_constants.php';
?>
//Sample Change

<html>
<head>
<title>The Saturday Quiz Sim</title>
<link rel='stylesheet' href='style.css' id='styler'>

</head>
<body>
<div class="container">
<div id="nocustom">
<header id="myHeader"></header>
<nav id="navBar">



</nav>
<article>

<h1>Simulation of</h1>
<p align="center"><img src="pics/tsq_logo.png"></img></p>

<p align="center"><a href="tsq_rules.html" target="new">Game Rules</a> . <a href="tsq_champions.php" target="new">Top Champions</a> . <a href="tsq100_display_games.php" target="new">100 Game Simulation</a></p>

<br>
<b>DISCLAIMERS: </b>
<ul>
<li>I did borrow a little styling from the <a href="http://www.j-archive.com" target="new">J-Archive</a>.</li>	
<li>The contestant names you see were either made up or randomly generated by <a href="http://www.fakenamegenerator.com/" target="new">Fake Name Generator</a>.  Any relation to any persons, living or dead, are entirely coincidental, especially with Show #1; that was just a lucky roll of the virtual dice!</li>
<li><b><u>NO REAL MONEY NOR PRIZES ARE AWARDED.</u></b>  This is just a simulation.</li>
<li>There is no trademark for The Saturday Quiz.  If anyone legally owns the name The Saturday Quiz, please <a href="mailto:tsd@thesweepingdeveloper.com">e-mail me</a> to request removal.</li>
</ul>

<?php
//Step2
$season_query = "SELECT DISTINCT `season` FROM `TSQ Games`";
mysqli_query($db, $season_query) or die('Error querying season list.');
$season_result = mysqli_query($db, $season_query);

$game_query = "SELECT * FROM `TSQ Games` WHERE `season` = ".$_GET["season"]. " ORDER BY `air_date` DESC, `id` DESC";
mysqli_query($db, $game_query) or die('Error querying database.');


$game_result = mysqli_query($db, $game_query);
?>



<?php

echo "<p align='center'>Seasons: ";
while ($season_row = mysqli_fetch_array($season_result))
{
	$curr_season = $_GET["season"];
	if ($curr_season == $season_row['season'])
	{
		echo $season_row['season']."   ";
	}
	else
	{
		echo "<a href='tsq.php?season=".$season_row['season']."'>".$season_row['season']."   ";
	}
}
echo "</p>";



echo "<p align='center'><table><tr><td>Airdate</td><td>Player 1</td><td>Player 2</td><td>Player 3</td><td>Comments</td></tr>";
while ($game_row = mysqli_fetch_array($game_result)) 
{

	$p1_query = "SELECT * FROM `TSQ Contestants` WHERE `id` = ".$game_row['c1_id'];
	$p1_result = mysqli_query($db, $p1_query) or die ('Error querying contestant 1 data.');
	$p1_row = mysqli_fetch_array($p1_result);
	
	$p2_query = "SELECT * FROM `TSQ Contestants` WHERE `id` = ".$game_row['c2_id'];
	$p2_result = mysqli_query($db, $p2_query) or die ('Error querying contestant 2 data.');
	$p2_row = mysqli_fetch_array($p2_result);
	
	$p3_query = "SELECT * FROM `TSQ Contestants` WHERE `id` = ".$game_row['c3_id'];
	$p3_result = mysqli_query($db, $p3_query) or die ('Error querying contestant 3 data.');
	$p3_row = mysqli_fetch_array($p3_result);
	
	
	echo "<tr><td><a href='tsq_game.php?game_id=".$game_row['id']."'>".$game_row['air_date']."</a></td>";
	echo "<td";
	if ($game_row['c1_championships'] > 0) { echo " style='color:yellow'><b>"; } else { echo ">"; }
	echo $p1_row['fname']." ".$p1_row['lname'];
	if ($game_row['c1_championships'] > 0) { echo "</b>"; }
	echo "</td><td";
	if ($game_row['c2_championships'] > 0) { echo " style='color:yellow'><b>"; } else { echo ">"; }
	echo $p2_row['fname']." ".$p2_row['lname'];
	if ($game_row['c2_championships'] > 0) { echo "</b>"; }
	echo "</td><td";
	if ($game_row['c3_championships'] > 0) { echo " style='color:yellow'><b>"; } else { echo ">"; }
	echo $p3_row['fname']." ".$p3_row['lname'];
	if ($game_row['c3_championships'] > 0) { echo "</b>"; }
	echo "</td><td>";
	echo $game_row['comments']."</td></tr>";
	
	
	
}
echo "</table></p>";
?>

<?php

	for ($a = 1; $a <= 20; $a++)
	{
		echo '<br>';
	}

?>

</article>
<footer id="myFooter"></footer>
<script src="elements.js"></script>
</div>
</div>
</body>
</html>

