<?php
include 'tsq_constants.php';

?>


<html>
<head>
<title>The Saturday Quiz Sim</title>
<link rel='stylesheet' href='style.css' id='styler'>

</head>
<body>
<div class="container">
<div id="nocustom">
<header id="myHeader"></header>
<nav id="navBar">

</nav>
<article>

<br>
<br>

<b>DISCLAIMERS: </b>
<ul>
<li>The contestant names you see were either made up or randomly generated by <a href="http://www.fakenamegenerator.com/" target="new">Fake Name Generator</a>.  Any relation to any persons, living or dead, are entirely coincidental, especially with Show #1; that was just a lucky roll of the virtual dice!</li>
<li><b><u>NO REAL MONEY NOR PRIZES ARE AWARDED.</u></b>  This is just a simulation.</li>
<li>There is no trademark for The Saturday Quiz.  If anyone legally owns the name The Saturday Quiz, please <a href="mailto:tsd@thesweepingdeveloper.com">e-mail me</a> to request removal.</li>
</ul>

<?php

$game_query = "SELECT * FROM `TSQ100 Games` ORDER BY `id` ASC";
mysqli_query($db, $game_query) or die('Error querying database.');


$game_result = mysqli_query($db, $game_query);



echo "<p align='center'><table><tr><td>Airdate</td><td>Player 1</td><td>Player 2</td><td>Player 3</td><td>Comments</td></tr>";
while ($game_row = mysqli_fetch_array($game_result)) 
{

	$p1_query = "SELECT * FROM `TSQ100 Contestants` WHERE `id` = ".$game_row['c1_id'];
	$p1_result = mysqli_query($db, $p1_query) or die ('Error querying contestant 1 data.');
	$p1_row = mysqli_fetch_array($p1_result);
	
	$p2_query = "SELECT * FROM `TSQ100 Contestants` WHERE `id` = ".$game_row['c2_id'];
	$p2_result = mysqli_query($db, $p2_query) or die ('Error querying contestant 2 data.');
	$p2_row = mysqli_fetch_array($p2_result);
	
	$p3_query = "SELECT * FROM `TSQ100 Contestants` WHERE `id` = ".$game_row['c3_id'];
	$p3_result = mysqli_query($db, $p3_query) or die ('Error querying contestant 3 data.');
	$p3_row = mysqli_fetch_array($p3_result);
	
	
	echo "<tr><td><a href='tsq100_game.php?game_id=".$game_row['id']."'>".$game_row['air_date']."</a></td>";
	echo "<td";
	if ($game_row['c1_championships'] > 0) { echo " style='color:yellow'><b>"; } else { echo ">"; }
	echo $p1_row['fname']." ".$p1_row['lname'];
	if ($game_row['c1_championships'] > 0) { echo "</b>"; }
	echo "</td><td";
	if ($game_row['c2_championships'] > 0) { echo " style='color:yellow'><b>"; } else { echo ">"; }
	echo $p2_row['fname']." ".$p2_row['lname'];
	if ($game_row['c2_championships'] > 0) { echo "</b>"; }
	echo "</td><td";
	if ($game_row['c3_championships'] > 0) { echo " style='color:yellow'><b>"; } else { echo ">"; }
	echo $p3_row['fname']." ".$p3_row['lname'];
	if ($game_row['c3_championships'] > 0) { echo "</b>"; }
	echo "</td><td>";
	
	
	if (substr($game_row['comments'],0,1) != "*")
	{
		echo $game_row['comments']."</td></tr>";
	}
	else
	{
		echo substr($game_row['comments'], 1, strlen($game_row['comments'])-1)."</td></tr>";
	}
	
	
	
	
	
}
echo "</table></p>";
?>

<?php

	
	//Top Champions
	

	echo ('<h1><p align="center"><b>Top Nine Champions</b></p></h1>');
	echo ('<table border="1" align="center">');
	$games_required = array(7,5);
	$season = 2;
	$contestant_data = [];
	$contestant_list = [];
	$contestant_duplicates = [];
	$final_list_data = [];


	$query = "SELECT `Contestants`.`fname`, `Contestants`.`lname`, `Games`.`c3_id`, IF (`Games`.`c3_winnings` >= 1000000, `Games`.`c3_championships` + 1, `Games`.`c3_championships`), `Games`.`c3_level`, `Games`.`c3_winnings` 
			  FROM sdevelop_youtube.`TSQ100 Games` AS `Games`, sdevelop_youtube.`TSQ100 Contestants` AS `Contestants` 
			  WHERE `season` = 2 AND `Games`.`mode` = 0 AND `c3_id` = `Contestants`.`id` 
			  ORDER BY IF (`Games`.`c3_winnings` >= 1000000, `Games`.`c3_championships` + 1, `Games`.`c3_championships`) DESC, `c3_level` DESC, `c3_winnings` DESC;";
	$result = mysqli_query($db, $query) or die ('Error querying game data for Contestant #3.');

	while ($row = mysqli_fetch_array($result))
	{
		array_push($contestant_data, $row);
	}

	$query = "SELECT `Contestants`.`fname`, `Contestants`.`lname`, `Games`.`c2_id`, IF (`Games`.`c2_winnings` >= 1000000, `Games`.`c2_championships` + 1, `Games`.`c2_championships`), `Games`.`c2_level`, `Games`.`c2_winnings` 
			  FROM sdevelop_youtube.`TSQ100 Games` AS `Games`, sdevelop_youtube.`TSQ100 Contestants` AS `Contestants` 
			  WHERE `season` = 2 AND `Games`.`mode` = 0 AND `c2_id` = `Contestants`.`id` 
			  ORDER BY IF (`Games`.`c2_winnings` >= 1000000, `Games`.`c2_championships` + 1, `Games`.`c2_championships`) DESC, `c2_level` DESC, `c2_winnings` DESC;";
	$result = mysqli_query($db, $query) or die ('Error querying game data for Contestant #2.');

	while ($row = mysqli_fetch_array($result))
	{
		array_push($contestant_data, $row);
	}

	$query = "SELECT `Contestants`.`fname`, `Contestants`.`lname`, `Games`.`c1_id`, IF (`Games`.`c1_winnings` >= 1000000, `Games`.`c1_championships` + 1, `Games`.`c1_championships`), `Games`.`c1_level`, `Games`.`c1_winnings` 
			  FROM sdevelop_youtube.`TSQ100 Games` AS `Games`, sdevelop_youtube.`TSQ100 Contestants` AS `Contestants` 
			  WHERE `season` = 2 AND `Games`.`mode` = 0 AND `c1_id` = `Contestants`.`id` 
			  ORDER BY IF (`Games`.`c1_winnings` >= 1000000, `Games`.`c1_championships` + 1, `Games`.`c1_championships`) DESC, `c1_level` DESC, `c1_winnings` DESC;";
	$result = mysqli_query($db, $query) or die ('Error querying game data for Contestant #1.');

	while ($row = mysqli_fetch_array($result))
	{
		array_push($contestant_data, $row);
	}
	$num_of_entries = sizeof($contestant_data) / 3;
	for ($a = 0; $a <= 2; $a++)
	{
		
		#echo ("Contestant Position #".(3-$a).":\n");
		for ($b = 0; $b <= $num_of_entries - 1; $b++)
		{
			$index = $a * $num_of_entries + $b;
			#echo ($contestant_data[$index][2]);
			if (in_array($contestant_data[$index][2], $contestant_list) and in_array($contestant_data[$index][2], $contestant_duplicates) == false)
			{
				array_push($contestant_duplicates, $contestant_data[$index][2]);
			}
			else if (in_array($contestant_data[$index][2], $contestant_list) == false and in_array($contestant_data[$index][2], $contestant_duplicates) == false)
			{
				array_push($contestant_list, $contestant_data[$index][2]);
				array_push($final_list_data, $contestant_data[$index]);
			}
			
		}
		echo ("\n");
	}

	#echo ("Contestant Duplicate IDs:\n");
	#for ($a = 0; $a <= sizeof($contestant_duplicates); $a++)
	#{
	#	echo ($contestant_duplicates[$a]."\n");
	#}
	#echo ("\nContestant List:\n");

	echo ('<tr>
			<th>Rank</th>
			<th>Player Name</th>
			<th>Championships</th>
			<th>Level Reached</th>
			<th>"Winnings"</th>
		  </tr>');
		  
	for ($a = 1; $a <= 9; $a++)
	{
		$f_name = $final_list_data[$a-1][0];
		$l_name = $final_list_data[$a-1][1];
		$championships = $final_list_data[$a-1][3];
		$level_reached = $final_list_data[$a-1][4];
		$winnings = $final_list_data[$a-1][5];
		echo ('<tr>
			   <td>'. $a .'</td>
			   <td>'. $f_name.' '.$l_name.'</td>
			   <td>'. $championships .'</td>
			   <td>'. $level_reached .'</td>
			   <td>$'. number_format($winnings) .'</td></tr>');
		
		#echo($final_list_data[$a][0]."\n");
	}

	echo ('</table>');



	


	
	
	
	





	for ($a = 1; $a <= 20; $a++)
	{
		echo '<br>';
	}

?>

</article>
<footer id="myFooter"></footer>
<script src="elements.js"></script>
</div>
</div>
</body>
</html>

