<?php
define ('constants', TRUE);
include 'tsq_constants.php';
?>


<html>
<head>
<title>The Saturday Quiz Sim</title>
<link rel='stylesheet' href='style.css' id='styler'>

</head>
<body>
<div class="container">

<header id="myHeader"></header>
<nav id="navBar">

</nav>
<article>

<br>
<br>

<b>DISCLAIMERS: </b>
<ul>
<li>The contestant names you see were either made up or randomly generated by <a href="http://www.fakenamegenerator.com/" target="new">Fake Name Generator</a>.  Any relation to any persons, living or dead, are entirely coincidental, especially with Show #1; that was just a lucky roll of the virtual dice!</li>
<li><b><u>NO REAL MONEY NOR PRIZES ARE AWARDED.</u></b>  This is just a simulation.</li>
<li>There is no trademark for The Saturday Quiz.  If anyone legally owns the name The Saturday Quiz, please <a href="mailto:tsd@thesweepingdeveloper.com">e-mail me</a> to request removal.</li>
</ul>

<?php
//$data_stream = "5122424136543361636556556131626122344462611356321612112146425143121642253226136141124133143663664464541256425243235313644535435562231541214461364231212454514362225353225242655632634563325313423541216523125336452154352243436645621334416116662623225412";
//$data_stream_timestamp = "2017-12-11 01:21:18 UTC";

//echo ('Deleting previous games...');
//clearAllGames();




#$player_query = "SELECT * FROM `TSQ100 Contestants`";
#$player_result = mysqli_query($db, $player_query) or die ('Error querying TSQ100 Contestants.');



$contestant_counter = 0;
//Original variables
for ($a = 0; $a <= 2; $a++)
{
	#$player_row = mysqli_fetch_array($player_result);
	$contestant_id[$a] = getNextContestant();

}
$game_script = array('','','','');
$contestant_championships = array(0,0,0);
$contestant_prior_winnings = array(0,0,0);
$contestant_level = array(1,1,1);

$contestant_game_skill_level = array(0,0,0);
$current_air_date = '2019-03-07';
$new_order = array(0,1,2);
//Generate random game skill level values for the first game.
echo ('About to generate game skill levels for first game.<br>');


echo ('<br>Starting 100 game simulation.<br>');


// *** START OF 100 GAME SIMULATION LOOP ***
for ($g = 1; $g <= 3; $g++)
{
	$rebound_pot = 0;
	$round_to_beat = -1;
	echo ('Start of Game #'.$g.'.<br>');
	//INSERT INTO `sdevelop_youtube`.`TSQ Games` (`timestamp`, `air_date`, `season`, `mode`,
	//`c1_id`, `c1_game_skill_level`, `c1_level`, `c1_championships`, `c1_prior_winnings`, `c1_winnings`, 
	//`c2_id`, `c2_game_skill_level`, `c2_level`, `c2_championships`, `c2_prior_winnings`, `c2_winnings`,
	//`c3_id`, `c3_game_skill_level`, `c3_level`, `c3_championships`, `c3_prior_winnings`, `c3_winnings`, `comments`, `data_stream`)
	//VALUES ('Testing for new project.', '2019-03-03', '2', '0', 
	//'1', '6', '3', '0', '0', '0',
	//'2', '6', '3', '2', '300000', '0',
	//'3', '6', '3', '5', '500000', '0', 
	//'Test game.', '666666666666666666666666666666666666666666666666666666666666666666666666666666666');

	
	for ($a = 0; $a <= 2; $a++)
	{
		echo 'Contestant winnings from last game:'.strval($contestant_winnings[$a]);
		if ($contestant_championships[$a] > 0)
		{
			$new_id[$a] = $contestant_id[$a];
			$new_contestant_championships[$a] = $contestant_championships[$a];
			$new_contestant_prior_winnings[$a] = $contestant_winnings[$a];
			$new_contestant_level[$a] = $contestant_level[$new_order[$a]];
		}
		else	
		{
			$new_id[$a] = getNextContestant();
			$new_contestant_championships[$a] = 0;
			$new_contestant_prior_winnings[$a] = 0;
			$new_contestant_level[$a] = 1;
		}
		$contesant_winnings[$a] = 0;
	}
	
	for ($a = 0; $a <= 2; $a++)
	{
		$contestant_id[$a] = $new_id[$a];
		$contestant_championships[$a] = $new_contestant_championships[$a];
		$contestant_prior_winnings[$a] = $new_contestant_prior_winnings[$a];
		$contestant_level[$a] = $new_contestant_level[$a];
	}
	
	for ($a = 0; $a <= 2; $a++)
	{
		$contestant_game_skill_level[$a] = rand(1,6);
	}

	//Generate data stream.
	echo ('Generating data stream for Game # '.strval($g).'.<br>');
	
	$data_stream = "";
	for ($a = 1; $a <= 250; $a++)
	{
		$data_stream = $data_stream . strval(rand(1,6));
	}
	echo ('Data stream is: '.$data_stream.'<br>');
	
	
	//Generate game.
	echo ('Querying Game #'.$g.' into MySQL server.<br>');
	$game_query = 
	"INSERT INTO `sdevelop_youtube`.`TSQ100 Games`
	(`id`, `timestamp`,`air_date`, `season`,`mode`,
	`c1_id`, `c1_game_skill_level`, `c1_level`, `c1_championships`, `c1_prior_winnings`, `c1_winnings`, 
	`c2_id`, `c2_game_skill_level`, `c2_level`, `c2_championships`, `c2_prior_winnings`, `c2_winnings`,
	`c3_id`, `c3_game_skill_level`, `c3_level`, `c3_championships`, `c3_prior_winnings`, `c3_winnings`, `comments`, `data_stream`)
	VALUES (".$g.", 'Game #".$g.".', '".$current_air_date."', '2', '0', 
	'".$contestant_id[0]."', '".$contestant_game_skill_level[0]."', '".$contestant_level[0]."', '".$contestant_championships[0]."', '".$contestant_prior_winnings[0]."', '0',
	'".$contestant_id[1]."', '".$contestant_game_skill_level[1]."', '".$contestant_level[1]."', '".$contestant_championships[1]."', '".$contestant_prior_winnings[1]."', '0',
	'".$contestant_id[2]."', '".$contestant_game_skill_level[2]."', '".$contestant_level[2]."', '".$contestant_championships[2]."', '".$contestant_prior_winnings[2]."', '0',
	'Game #".$g.".', '".$data_stream."')
	";

	$game_result = mysqli_query($db, $game_query) or die ('Error generating Game #'.$g.'.');
	$game_row = mysqli_fetch_array($game_result);

	
	//DELETE FROM `TSQ100 Games` WHERE `id` = 1;
	//ALTER TABLE `TSQ100 Games` AUTO_INCREMENT = 1;
	//Retrieve said game.
	//echo ('Retrieving Game #'.$g.'.<br>');
	$retrieve_query = "SELECT * FROM `TSQ100 Games` WHERE `id` = ".strval($g);

	$retrieve_result = mysqli_query($db, $retrieve_query) or die ('Error retrieving Game #'.$g.'.');
	$retrieve_row = mysqli_fetch_array($retrieve_result);

	$p1_query = "SELECT * FROM `TSQ100 Contestants` WHERE id = ".$retrieve_row['c1_id'];
	$p1_result = mysqli_query($db, $p1_query) or die ('Error querying contestant 1 data.');
	$p1_row = mysqli_fetch_array($p1_result);
	
	$p2_query = "SELECT * FROM `TSQ100 Contestants` WHERE id = ".$retrieve_row['c2_id'];
	$p2_result = mysqli_query($db, $p2_query) or die ('Error querying contestant 2 data.');
	$p2_row = mysqli_fetch_array($p2_result);
	
	$p3_query = "SELECT * FROM `TSQ100 Contestants` WHERE id = ".$retrieve_row['c3_id'];
	$p3_result = mysqli_query($db, $p3_query) or die ('Error querying contestant 3 data.');
	$p3_row = mysqli_fetch_array($p3_result);
		
	$contestant_id[0] = $p1_row['id'];
	$contestant_fname[0] = $p1_row['fname'];
	$contestant_lname[0] = $p1_row['lname'];
	$contestant_occupation[0] = $p1_row['occupation'];
	$contestant_city[0] = $p1_row['city'];
	$contestant_state[0] = $p1_row['state'];
	$contestant_initial_skill_level[0] = $p1_row['init_skill_level'];
	
	$contestant_id[1] = $p2_row['id'];
	$contestant_fname[1] = $p2_row['fname'];
	$contestant_lname[1] = $p2_row['lname'];
	$contestant_occupation[1] = $p2_row['occupation'];
	$contestant_city[1] = $p2_row['city'];
	$contestant_state[1] = $p2_row['state'];
	$contestant_initial_skill_level[1] = $p2_row['init_skill_level'];
	
	$contestant_id[2] = $p3_row['id'];
	$contestant_fname[2] = $p3_row['fname'];
	$contestant_lname[2] = $p3_row['lname'];
	$contestant_occupation[2] = $p3_row['occupation'];
	$contestant_city[2] = $p3_row['city'];
	$contestant_state[2] = $p3_row['state'];
	$contestant_initial_skill_level[2] = $p3_row['init_skill_level'];	
	
	//Begin game.
	$season = $retrieve_row['season'] - 1;
	
	$mode = $retrieve_row['mode'];
	
	if ($mode == 1)
	{
		$rebound_pot = 40000;
	}
	if ($mode == 2)
	{
		$rebound_pot = 100000;
	}
	

	$data_stream = $retrieve_row['data_stream'];
	$data_stream_timestamp = $retrieve_row['timestamp'];

	for ($a = 0; $a <= 2; $a++)
	{
		$round = 1;
		$victory = 0;
		$fail = 0;
		//echo '<h2>' . $contestant_fname[$a] . ' ' . $contestant_lname[$a] . '</h2>';
		
		if ($contestant_initial_skill_level[$a] == 0) 
			{
				$contestant_initial_skill_level[$a] = getNextNumber();
				$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Contestants` SET `init_skill_level` = '".$contestant_initial_skill_level[$a]."' WHERE `TSQ100 Contestants`.`id` = '".$contestant_id[$a]."'";
				$game_result = mysqli_query($db, $game_query) or die ('Error querying initial skill level of Contestant '.$a.'.');
				//$game_row = mysqli_fetch_array($game_result);
			}
		
		if ($contestant_game_skill_level[$a] == 0) 
			{
				$contestant_game_skill_level[$a] = getNextNumber();
			}

			   //if ($a == 0)  {$game_query = "UPDATE `TSQ Games` SET `c1_game_skill_level` = '".$contestant_game_skill_level[0]."' WHERE `id` = '".$_GET["game_id"]."'";}
			   //if ($a == 1)  {$game_query = "UPDATE `TSQ Games` SET `c2_game_skill_level` = '".$contestant_game_skill_level[1]."' WHERE `id` = '".$_GET["game_id"]."'";}
			   //if ($a == 2)  {$game_query = "UPDATE `TSQ Games` SET `c3_game_skill_level` = '".$contestant_game_skill_level[2]."' WHERE `id` = '".$_GET["game_id"]."'";}
				//$game_result = mysqli_query($db, $game_query) or die ('Error querying game skill level of Contestant '.$a.'.');
				//$game_row = mysqli_fetch_array($game_result);		//Error here.
		
		$total_skill_level = $contestant_initial_skill_level[$a] + $contestant_game_skill_level[$a];
		
		
		//echo '<b>Initial Skill Level: ' . $contestant_initial_skill_level[$a].'</b><br>';
		//echo '<b>Game Skill Level: '.$contestant_game_skill_level[$a].', for a total of '.$total_skill_level . '<br><br>';
	
		//echo '<table border="1">';
		do		//Beginning of Round.
		{
			
			//echo '<tr>';
			if ($contestant_level[$a] == 1)
			{
				//echo '<td style="color:white; text-shadow: 2px 2px 3px black">$'.number_format($round_values[$season][$round - 1]).'</td>';
			}
			if ($contestant_level[$a] == 2)
			{
				//echo '<td style="color:white; text-shadow: 2px 2px 3px black">$'.number_format($round_values[$season][$round - 1] * 2).'</td>';
			}
			if ($contestant_level[$a] == 3 && $season == 0)
			{
				//echo '<td style="color:white; text-shadow: 2px 2px 3px black">$'.number_format($round_values[$season][$round - 1] * 4).'</td>';
			}
			if ($contestant_level[$a] == 3 && $season > 0 && $round < 7)
			{
				//echo '<td style="color:linear-gradient(gold, yellow); text-shadow: 2px 2px 3px black">$'.number_format($round_values[$season][$round - 1] * 5).'</td>';
			}
			if ($contestant_level[$a] == 3 && $season > 0 && $round == 7)
			{
				if ($mode == 0)
				{
					//echo '<td style="background: linear-gradient(gold, yellow); color:Black; text-shadow: 2px 2px 3px white"><b>$1 MILLION</b></td>';
				}
				if ($mode == 2)
				{
					//echo '<td style="color:white; text-shadow: 2px 2px 3px black">$500,000</td>';
				}
				
			}				
			
			if ($contestant_level[$a] == 4 && $round < 7) 
			{
				//echo '<td style="color:gold; text-shadow: 2px 2px 3px black">$'.number_format($round_values[$season][$round - 1] * 10).'</td>';
			}
			if ($contestant_level[$a] == 4 && $round == 7)
			{
				//echo '<td style="background: linear-gradient(gold, yellow); color: Black; text-shadow: 2px 2px 3px white"><b>$1 MILLION</b></td>';
			}

			
			$questions_left = 7 + $contestant_wildcards[$a];
			$questions_get = 0;
			$questions_used = 0;
 
			//Question Routine.
			do
			{
				//echo '<td';
				$data_stream_value = getNextNumber();
				if ($data_stream_value >= $skill_correct_first_roll[$total_skill_level])
				{
					//echo ' style="background: linear-gradient(green, lime); color:black"><b>O</b>';
					$questions_get++;
				}
				else
				{
					if ($skill_correct_second_roll_needed[$total_skill_level] == 1)
					{
						$data_stream_value = getNextNumber();
						if ($data_stream_value >= $skill_correct_second_roll[$total_skill_level])
						{
							//echo ' style="background: linear-gradient(green, lime); color:black"><b>O</b>';
							$questions_get++;
						}
						else
						{
							//echo ' style="background: linear-gradient(maroon, red); color:black"><b>X</b>';
						}
					}
					else
					{
						//echo ' style="background: linear-gradient(maroon, red); color:black"><b>X</b>';
					}
				}
				//echo '</td>';
				$questions_left--;
				$questions_used++;
				
			}
			while ($questions_get < $questions_needed[$round-1] && $questions_get + $questions_left >= $questions_needed[$round-1] && $questions_left > 0);
			//echo '</tr>';
			
			if ($questions_used > 7) {$contestant_wildcards[$a] += 7-$questions_used;}
			
			//Check for failure.
			if ($questions_get + $questions_left < $questions_needed[$round-1])
			{
				$fail = 1;
			}
			
			//Check for a victory (Clearing all seven rounds in a level).
			if ($fail == 0 && $round == 7)
			{
				$victory = 1;
			}				
			
			//Check for a continue condition if the player didn't fail nor cleared the board.
			if ($fail == 0 && $victory == 0 && $questions_left <= 3)
			{                
				$roll_index = (($round-1)*4 + (3-$questions_left))+ $skill_table_round_adj[$contestant_level[$a] - 1] + $skill_table_skill_adj[$total_skill_level];
				//echo $round.', '.$questions_left.', '.$skill_table_round_adj[$contestant_level[$a] - 1].', '.$skill_table_skill_adj[$total_skill_level].'<br>';
				$data_stream_value = getNextNumber();
				//echo 'Questions left: '.$questions_left.', Round: '.$round.', Roll Index: '.$roll_index.', Roll #'.$data_stream_counter.': '.$data_stream_value.' vs. '.$skill_table_first_roll[$roll_index].'<br>'; 
				if ($data_stream_value >= $skill_table_first_roll[$roll_index])
				{
					$continue = 1;
				}
				else
				{
					if ($skill_table_second_roll_needed[($round-1)*4 + (3-$questions_left)] == 1)
					{
						
						$data_stream_value = getNextNumber();
						//echo 'Roll #'.$data_stream_counter.' is a second chance, and it is: '.$data_stream_value.'<br>';
						//echo 'OK, what is the skill table second roll dude?<br>';
						//echo 'Computer: It is '.$skill_table_second_roll[$roll_index].'<br>';
						if ($data_stream_value >= $skill_table_second_roll[$roll_index])
						{
							$continue = 1;
						}
						else
						{
							$continue = 0;
						}
					}
					else
					{
						$continue = 0;
					}
					
				}
			}
			else
			{
				$continue = 1;
			}
			
			
			
			
			$round++;
		}
		while ($continue == 1 && $victory == 0 && $fail == 0);
		
		
		

	//echo '</table><br>';
	//echo 'Contestant wildcards left: '.$contestant_wildcards[$a].'<br>';
		
	

		if ($continue == 0 && $fail == 0 && $victory == 0)
		{
			//echo '<div id="dropout">';
			if ($season == 0)
			{
				$contestant_round_reached[$a] = $round - 2;
				
				if ($round_to_beat < $contestant_round_reached[$a])  {$round_to_beat = $contestant_round_reached[$a];}
					
				if ($contestant_level[$a] == 1) {$contestant_winnings[$a] += $round_values[$season][$round - 2]; }//echo $contestant_fname[$a]. ' stops on $'. number_format($round_values[$season][$round - 2]).'.';}
				if ($contestant_level[$a] == 2) {$contestant_winnings[$a] += $round_values[$season][$round - 2] * 2; }//echo $contestant_fname[$a]. ' stops on $'. number_format($round_values[$season][$round - 2] * 2).'.';}
				if ($contestant_level[$a] == 3) {$contestant_winnings[$a] += $round_values[$season][$round - 2] * 4; }//echo $contestant_fname[$a]. ' stops on $'. number_format($round_values[$season][$round - 2] * 4).'.';}
				if ($contestant_level[$a] == 4) {$contestant_winnings[$a] += $round_values[$season][$round - 2] * 10; }//echo $contestant_fname[$a]. ' stops on $'. number_format($round_values[$season][$round - 2] * 10).'.';}

			}
			else if ($season > 0)
			{
				$contestant_round_reached[$a] = $round - 2;
				
				if ($round_to_beat < $contestant_round_reached[$a])  {$round_to_beat = $contestant_round_reached[$a];}
					
				if ($contestant_level[$a] == 1) {$contestant_winnings[$a] += $round_values[$season][$round - 2]; }//echo $contestant_fname[$a]. ' stops on $'. number_format($round_values[$season][$round - 2]).'.';}
				if ($contestant_level[$a] == 2) {$contestant_winnings[$a] += $round_values[$season][$round - 2] * 2; }//echo $contestant_fname[$a]. ' stops on $'. number_format($round_values[$season][$round - 2] * 2).'.';}
				if ($contestant_level[$a] == 3) {$contestant_winnings[$a] += $round_values[$season][$round - 2] * 5; }//echo $contestant_fname[$a]. ' stops on $'. number_format($round_values[$season][$round - 2] * 5).'.';}

			}
			//echo '</div><br>';
		}
		
	
		if ($victory == 1)
		{
			//echo '<div id="seikai">';
			if ($season == 0)
			{
				if ($contestant_level[$a] == 1) {$contestant_winnings[$a] += 50000;  }//echo $contestant_fname[$a]. ' clears Level 1 and wins $50,000!';}
				if ($contestant_level[$a] == 2) {$contestant_winnings[$a] += 100000; }//echo $contestant_fname[$a]. ' clears Level 2 and wins $100,000!';}
				if ($contestant_level[$a] == 3) {$contestant_winnings[$a] += 200000; }//echo $contestant_fname[$a]. ' clears Level 3 and wins $200,000!';}
				if ($contestant_level[$a] == 4) 
					{$contestant_winnings[$a] += 1000000;  }//echo '<u><i>'.$contestant_fname[$a]. ' CLEARS LEVEL 4 AND WINS $1 MILLION!</i></u>';}
				$contestant_level[$a]++;
				$contestant_round_reached[$a] = $round - 2;
				if ($round_to_beat < $contestant_round_reached[$a])  {$round_to_beat = $contestant_round_reached[$a];}				
			}
			else if ($season > 0)
			{
				if ($contestant_level[$a] == 1) {$contestant_winnings[$a] += 100000;  }//echo $contestant_fname[$a]. ' clears Level 1 and wins $100,000!</b></h2><br>';}
				if ($contestant_level[$a] == 2) 
					{
						if ($mode == 0)
						{
							$contestant_winnings[$a] += 200000; //echo $contestant_fname[$a]. ' clears Level 2 and wins $200,000!</b></h2><br>';
						}
						if ($mode > 0)
						{
							$contestant_winnings[$a] += 200000; //echo $contestant_fname[$a]. ' clears the board and wins $200,000!</b></h2><br>';
						}

					}
				if ($contestant_level[$a] == 3) 
					{
						if ($mode == 0)
						{
							$contestant_winnings[$a] += 1000000;  //echo '<u><i>'.$contestant_fname[$a]. ' JUST WON A MILLION DOLLARS!</i></u>';
						}
						if ($mode > 0)
						{
							$contestant_winnings[$a] += 500000;  //echo $contestant_fname[$a]. ' clears the board and wins $500,000!';
						}
						
						
						
					}
				$contestant_level[$a]++;
				$contestant_round_reached[$a] = $round - 2;
				if ($round_to_beat < $contestant_round_reached[$a])  {$round_to_beat = $contestant_round_reached[$a];}				
			}
			//echo '</div></b><br>';
		}
		
		
		if ($fail == 1 && $round > 1)
		{
			echo '<div id="zannen">';
			if ($season == 0)
			{
				if ($contestant_level[$a] == 1) { $rebound_pot += $round_values[$season][$round - 3]; }//echo '$'.number_format($round_values[$season][$round - 3]). ' put in pot.';}
				if ($contestant_level[$a] == 2) { $rebound_pot += $round_values[$season][$round - 3] * 2; }//echo '$'.number_format($round_values[$season][$round - 3] * 2). ' put in pot.';}
				if ($contestant_level[$a] == 3) { $rebound_pot += $round_values[$season][$round - 3] * 4; }//echo '$'.number_format($round_values[$season][$round - 3] * 4). ' put in pot.';}
				if ($contestant_level[$a] == 4) { $rebound_pot += $round_values[$season][$round - 3] * 10; }//echo 'ZANNEN!!!  $'.number_format($round_values[$season][$round - 3] * 10). ' put in pot.';}
			}
			else if ($season > 0)
			{
				if ($contestant_level[$a] == 1) { $rebound_pot += $round_values[$season][$round - 3]; }//echo '$'.number_format($round_values[$season][$round - 3]). ' put in pot.';}
				if ($contestant_level[$a] == 2) { $rebound_pot += $round_values[$season][$round - 3] * 2; }//echo '$'.number_format($round_values[$season][$round - 3] * 2). ' put in pot.';}
				if ($contestant_level[$a] == 3) { $rebound_pot += $round_values[$season][$round - 3] * 5; }//echo 'ZANNEN!!!  $'.number_format($round_values[$season][$round - 3] * 5). ' put in pot.';}
			}
			//echo '</div><br>';
		}
		if ($fail == 1)
		{
			$contestant_round_reached[$a] = 0;
		}
				//echo 'Round reached: '.($contestant_round_reached[$a]+1).'<br>';
		//$data_stream_counter--;
	}	//End of Regular part of show.
	
	
	
	
	//Start of rebound game loop.
	if ($rebound_pot > 0)
	{
		//echo 'Rebound game.<br>';
		$game_script[3] += "Rp";		//for "Rebound Pot"
		//Rebound game.

		for ($a = 0; $a <= 2; $a++)
		{	
			$rebound_score[$a] = 0;
		}

		//While nobody has yet scored five points...
		do
		{
			displayReboundTable();
			$game_script[3] += "??";		//for "Question", the second ? means it's for a rebound.
			
			for ($a = 0; $a <= 2; $a++){$rebound_active[$a] = 1;}
			
			$rebound_gofor = getNextNumber();
			if ($rebound_gofor == 1)
			{
				$game_script[3] += "Nb";	//for "No Buzz"	
			}
			if ($rebound_gofor > 1)
			{
				$rebound_first_pick = getNextNumber();
				$rebound_first_pick = ($rebound_first_pick - 1) % 3;

				for ($pr = 0; $pr <= 2; $pr++) {if ($rebound_first_pick == $pr) {$game_script[3] += "P"+strval($pr+1);}}
				
				$total_skill_level = $contestant_initial_skill_level[$rebound_first_pick] + $contestant_game_skill_level[$rebound_first_pick];

				
				//Determines whether or not your answer is correct.
				$data_stream_value = getNextNumber();
				if ($data_stream_value >= $skill_correct_first_roll[$total_skill_level])
				{
					//Correct
					$rebound_score[$rebound_first_pick]++;
					$rebound_right = 1;
					
					if ($rebound_score[$rebound_first_pick] == 5) {$game_script[3] += "G5";} else {$game_script[3] += "C"+ strval($rebound_score[$rebound_first_pick]);}	//for "Game 5" and "Correct n"
					//echo 'RIGHT<br><br>';
					//displayReboundTable();			
				}
				else
				{
					if ($skill_correct_second_roll_needed[$total_skill_level] == 1)
					{
						$data_stream_value = getNextNumber();
						if ($data_stream_value >= $skill_correct_second_roll[$total_skill_level])
						{
							//Correct
							$rebound_score[$rebound_first_pick]++;
							$rebound_right = 1;
							if ($rebound_score[$rebound_first_pick] == 5) {$game_script[3] += "g5";} else {$game_script[3] += "c"+ strval($rebound_score[$rebound_first_pick]);}	//for "...Game 5" and "...Correct n"
							
							//echo 'RIGHT<br><br>';
							//displayReboundTable();
						}
						else
						{
							
							//Wrong
							$rebound_right = -1;
							$rebound_active[$rebound_first_pick] = 0;
							$game_script[3] += "wr"; 	//for "...Wrong"
							
							//echo 'WRONG<br>';
							
						}
					}
					else
					{
						//Wrong
						$rebound_right = -1;
						$rebound_active[$rebound_first_pick] = 0;
						$game_script[3] += "Wr"; 		//for "Wrong"
						
						//echo 'WRONG<br>';
					}
				}
				
				//If the first player is wrong, try another player.
				if ($rebound_right < 0)
				{
					if ($rebound_active[0] == 0) { $rebound_second_available[0] = 1; $rebound_second_available[1] = 2;}
					if ($rebound_active[1] == 0) { $rebound_second_available[0] = 0; $rebound_second_available[1] = 2;}
					if ($rebound_active[2] == 0) { $rebound_second_available[0] = 0; $rebound_second_available[1] = 1;}
					$rebound_gofor = getNextNumber();
					
					//If no one buzzes in...
					if ($rebound_gofor == 1)
					{
						$game_script[3] += "Nb";	//for "No Buzz"	
					}
					//If someone buzzes in...
					if ($rebound_gofor > 1)
					{
						$rebound_second_pick = getNextNumber();
						$rebound_second_pick = $rebound_second_available[$rebound_second_pick % 2];
						$total_skill_level = $contestant_initial_skill_level[$rebound_second_pick] + $contestant_game_skill_level[$rebound_second_pick];
						for ($pr = 0; $pr <= 2; $pr++) {if ($rebound_second_pick == $pr) {$game_script[3] += "P"+strval($pr+1);}}

						//echo '<b>'.$contestant_fname[$rebound_second_pick].': </b>';
						
						//Is that person right?
						$data_stream_value = getNextNumber();
						if ($data_stream_value >= $skill_correct_first_roll[$total_skill_level])
						{
							//Correct
							$rebound_score[$rebound_second_pick]++;
							$rebound_right = 1;
							if ($rebound_score[$rebound_second_pick] == 5) {$game_script[3] += "G5";} else {$game_script[3] += "C"+ strval($rebound_score[$rebound_second_pick]);}	//for "Game 5" and "Correct n"

							//echo 'RIGHT<br><br>';
							//displayReboundTable();
						}
						else
						{
							if ($skill_correct_second_roll_needed[$total_skill_level] == 1)
							{
								$data_stream_value = getNextNumber();
								if ($data_stream_value >= $skill_correct_second_roll[$total_skill_level])
								{
									//Correct
									$rebound_score[$rebound_second_pick]++;
									$rebound_right = 1;
									if ($rebound_score[$rebound_second_pick] == 5) {$game_script[3] += "g5";} else {$game_script[3] += "c"+ strval($rebound_score[$rebound_second_pick]);}	//for "...Game 5" and "...Correct n"
									
									//echo 'RIGHT<br><br>';
									//displayReboundTable();
								}
								else
								{
									
									//Wrong
									$rebound_right = -1;
									$rebound_active[$rebound_second_pick] = 0;
									$game_script[3] += "wr"; 	//for "...Wrong"
									//echo 'WRONG<br>';
								}
							}
							else
							{
								//Wrong
								$rebound_right = -1;
								$rebound_active[$rebound_second_pick] = 0;
								$game_script[3] += "Wr"; 		//for "Wrong"
								//echo 'WRONG<br>';
							}
						}	
								
						//If the second player is also wrong...
						if ($rebound_right < 0)
						{
							for ($a = 0; $a <= 2; $a++)  { if ($rebound_active[$a] == 1)  { $rebound_third_pick = $a; } }
							$total_skill_level = $contestant_initial_skill_level[$rebound_third_pick] + $contestant_game_skill_level[$rebound_third_pick];
							
							//echo ("Second player is also wrong in regular play.");
							$rebound_gofor = getNextNumber();
							
							//Stopped here: 6:47PM  1/14/2018
							
							if ($rebound_gofor == 1)
							{
								$game_script[3] += "Nb";	//for "No Buzz"
							}
							if ($rebound_gofor > 1)
							{
								//echo '<b>'.$contestant_fname[$rebound_third_pick].': </b>';
								//Is that person right?
								$data_stream_value = getNextNumber();
								if ($data_stream_value >= $skill_correct_first_roll[$total_skill_level])
								{
									//Correct
									$rebound_score[$rebound_third_pick]++;
									$rebound_right = 1;
									if ($rebound_score[$rebound_third_pick] == 5) {$game_script[3] += "G5";} else {$game_script[3] += "C"+ strval($rebound_score[$rebound_third_pick]);}	//for "Game 5" and "Correct n"
									
									//echo 'RIGHT<br><br>';
									//displayReboundTable();
								}
								else
								{
									if ($skill_correct_second_roll_needed[$total_skill_level] == 1)
									{
										$data_stream_value = getNextNumber();
										if ($data_stream_value >= $skill_correct_second_roll[$total_skill_level])
										{
											//Correct
											$rebound_score[$rebound_third_pick]++;
											$rebound_right = 1;
											if ($rebound_score[$rebound_third_pick] == 5) {$game_script[3] += "g5";} else {$game_script[3] += "c"+ strval($rebound_score[$rebound_third_pick]);}	//for "Game 5" and "Correct n"
											
											//echo 'RIGHT<br><br>';
											//displayReboundTable();
										}
										else
										{
											
											//Wrong
											$rebound_right = -1;
											$rebound_active[$rebound_third_pick] = 0;
											$game_script[3] += "wr"; 	//for "...Wrong"
											//echo 'WRONG<br><br>';
										}
									}
									else
									{
										//Wrong
										$rebound_right = -1;
										$rebound_active[$rebound_third_pick] = 0;
										$game_script[3] += "Wr"; 	//for "Wrong"
										//echo 'WRONG<br><br>';
									}
								}	

							}
						}
					}
				}
			}
		
			//echo '<br>';	
		}
		while ($rebound_score[0] < 5 && $rebound_score[1] < 5 && $rebound_score[2] < 5);
		
		//Determine the winner of the rebound pot.
		for ($a = 0; $a <= 2; $a++)
		{
			if ($rebound_score[$a] >= 5) 
			{
				//echo '<h2>'.$contestant_fname[$a].' wins the rebound pot of $'.number_format($rebound_pot).'!</h2><br><br>';
				$contestant_winnings[$a] += $rebound_pot;
				
				//Just in case everyone loses, the Rebound game determines the returning champion.
				if ($contestant_round_reached[0] == 0 && $contestant_round_reached[1] == 0 && $contestant_round_reached[2] == 0) {$contestant_round_reached[$a]++;  $round_to_beat = $contestant_round_reached[$a];}
			}

		}

	//End of Rebound Game loop.
	}
	
	$game_script[3] += "Rp"; 	//for "Rebound Pot"
	
	//Add all the winnings to the prior winnings.
	for ($a = 0; $a <= 2; $a++)
	{
		$contestant_winnings[$a] += $contestant_prior_winnings[$a];
		
		
	}
	
	//Final Scores for Regular Play.
	if ($mode == 0)
	{
		for ($a = 0; $a <= 2; $a++)
		{
			$retire_flag = 0;
			if ($contestant_round_reached[$a] >= $round_to_beat) 
			{
				if ($season == 0)
				{
					if ($contestant_championships[$a] % 10 < 6 && $contestant_level[$a] < 5)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is champion');
						$game_script[3] += "C"+strval($a+1);		//for "Player n is Champion"
						//echo '<h3>'.$contestant_fname[$a].' '.$contestant_lname[$a].' is coming back to play Level '.$contestant_level[$a].' with $'.number_format($contestant_winnings[$a]).'.</h3>';
					}
					else if ($contestant_championships[$a] % 10 > 5 && $contestant_level[$a] < 5)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is millionaire');
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `comments` = '*' WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error updating 5-time champion comment.');
						$contestant_championships[$a] -= 1;
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `c".strval($a+1)."_championships` = ".$contestant_championships[$a]." WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error adjusting millionaire championships number.');

						$contestant_winnings[$a] += 1000000;
						$retire_flag = 1;
						$game_script[3] += "M"+strval($a+1);		//for "Player n is Millionaire"
						$contestant_championships[$a] = 0;
						//echo '<h3>'.$contestant_fname[$a].' '.$contestant_lname[$a].' LEAVES AS A 7-TIME UNDEFEATED CHAMPION WITH $'.number_format($contestant_winnings[$a]).'!</h3>';
					}
					else if ($contestant_championships[$a] % 10 < 6 && $contestant_level[$a] > 4)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is millionaire');
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `comments` = '*' WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error updating 5-time champion comment.');
						$contestant_championships[$a] -= 1;
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `c".strval($a+1)."_championships` = ".$contestant_championships[$a]." WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error adjusting millionaire championships number.');
						$retire_flag = 1;
						$game_script[3] += "F"+strval($a+1);		//for "Player n Final Score"
						$contestant_championships[$a] = 0;
						//echo '<h3>'.$contestant_fname[$a].' '.$contestant_lname[$a].' is going home quite wealthy with $'.number_format($contestant_winnings[$a]).'.</h3>';
					}
					else if ($contestant_championships[$a] % 10 > 5 && $contestant_level[$a] > 4)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is millionaire');
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `comments` = '*' WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error updating 5-time champion comment.');
						$contestant_championships[$a] -= 1;
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `c".strval($a+1)."_championships` = ".$contestant_championships[$a]." WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error adjusting millionaire championships number.');
						$retire_flag = 1;
						$game_script[3] += "F"+strval($a+1);		//for "Player n Final Score"
						$contestant_winnings[$a] += 1000000;
						$contestant_championships[$a] = 0;
						//echo '<h3>Amazing.  '.$contestant_fname[$a].' '.$contestant_lname[$a].' has won both million dollar bonuses and is going home quite wealthy with $'.number_format($contestant_winnings[$a]).'.</h3>';
					}
					if ($retire_flag < 1)
					{
						$contestant_championships[$a]++;
					}
					
				}
				else if ($season > 0)
				{
					if ($contestant_championships[$a] % 10 < 4 && $contestant_level[$a] < 4)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is champion with $'.strval($contestant_winnings[$a]));
						$game_script[3] += "C"+strval($a+1);		//for "Player n is Champion"
						//echo '<h3>'.$contestant_fname[$a].' '.$contestant_lname[$a].' is coming back to play Level '.$contestant_level[$a].' with $'.number_format($contestant_winnings[$a]).'.</h3>';
					}
					else if ($contestant_championships[$a] % 10 > 3 && $contestant_level[$a] < 4)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is millionaire');
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `comments` = '*' WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error updating 5-time champion comment.');
						$contestant_championships[$a] -= 1;
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `c".strval($a+1)."_championships` = ".$contestant_championships[$a]." WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error adjusting millionaire championships number.');
						$retire_flag = 1;
						$contestant_winnings[$a] += 1000000;
						$game_script[3] += "M"+strval($a+1);		//for "Player n is Millionaire"
						$contestant_championships[$a] = 0;
						//echo '<h3>'.$contestant_fname[$a].' '.$contestant_lname[$a].' LEAVES AS A 5-TIME UNDEFEATED CHAMPION WITH $'.number_format($contestant_winnings[$a]).'!</h3>';
					}
					else if ($contestant_championships[$a] % 10 < 4 && $contestant_level[$a] > 3)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is millionaire');
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `comments` = '*' WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error updating 5-time champion comment.');
						$contestant_championships[$a] -= 1;
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `c".strval($a+1)."_championships` = ".$contestant_championships[$a]." WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error adjusting millionaire championships number.');
						$retire_flag = 1;
						$game_script[3] += "F"+strval($a+1);		//for "Player n Final Score"
						$contestant_championships[$a] = 0;
						//echo '<h3>'.$contestant_fname[$a].' '.$contestant_lname[$a].' is going home quite wealthy with $'.number_format($contestant_winnings[$a]).'.</h3>';
					}
					else if ($contestant_championships[$a] % 10 > 3 && $contestant_level[$a] > 3)
					{
						//echo ('Player '.strval($a).', '.$contestant_fname[$a].' is millionaire');
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `comments` = '*' WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error updating 5-time champion comment.');
						$contestant_championships[$a] -= 1;
						$game_query = "UPDATE `sdevelop_youtube`.`TSQ100 Games` SET `c".strval($a+1)."_championships` = ".$contestant_championships[$a]." WHERE `TSQ100 Games`.`id` = '".$g."'";
						$game_result = mysqli_query($db, $game_query) or die ('Error adjusting millionaire championships number.');
						$retire_flag = 1;
						$contestant_winnings[$a] += 1000000;
						$game_script[3] += "F"+strval($a+1);		//for "Player n Final Score"
						$contestant_championships[$a] = 0;
						//echo '<h3>Amazing.  '.$contestant_fname[$a].' '.$contestant_lname[$a].' has won both million dollar bonuses and is going home quite wealthy with $'.number_format($contestant_winnings[$a]).'.</h3>';
					}
					if ($retire_flag < 1)
					{
						$contestant_championships[$a]++;
					}
				}
				else
				{
					//echo '<h3>Head-On.  Apply directly to the forehead.</h3>';
				}
				
			}
			else
			{
				$game_script[3] += "F"+strval($a+1);		//for "Player n Final Score"
				//echo '<h3>'.$contestant_fname[$a].' '.$contestant_lname[$a].' leaves with $'.number_format($contestant_winnings[$a]).'.</h3>';
				$contestant_championships[$a] = 0;		//If a co-champion loses, don't allow that contestant to return.
			}
			
			
				   if ($a == 0)  {$final_query = "UPDATE `TSQ100 Games` SET `c1_winnings` = ".$contestant_winnings[0]." WHERE `id` = '".$g."'";}
				   if ($a == 1)  {$final_query = "UPDATE `TSQ100 Games` SET `c2_winnings` = ".$contestant_winnings[1]." WHERE `id` = '".$g."'";}
				   if ($a == 2)  {$final_query = "UPDATE `TSQ100 Games` SET `c3_winnings` = ".$contestant_winnings[2]." WHERE `id` = '".$g."'";}
					$final_result = mysqli_query($db, $final_query) or die ('Error querying day winnings of Contestant '.$a.'.');
					//$game_row = mysqli_fetch_array($game_result);
				echo 'Player '.$a.' championships: '.$contestant_championships[$a];
		}

	}
	
	//Write game script to database.
	/*
	for ($q = 0; $q <= 2; $q++)
	{
		$final_query = "UPDATE `TSQ100 Games` SET `game_script_".strval($q+1)."` = ".$game_script[$q]." WHERE `id` = ".strval($g);
		$final_result = mysqli_query($db, $final_query) or die ('Error querying for game script '.strval($q+1).'.');
	}

	$final_query = "UPDATE `TSQ100 Games` SET `game_script_rebound` = ".$game_script[3]." WHERE `id` = ".strval($g);
	$final_result = mysqli_query($db, $final_query) or die ('Error querying for rebound game script.');
	*/
	
	//See who is champion for next game.
	/*
	$championships_to_beat = 0;
	$challengers = 0;
	$new_positions = array(0,0,0);
	$new_id = array(0,0,0);
	$new_fname = array('','','');
	$new_lname = array('','','');
	$new_occupation = array('','','');
	$new_city = array('','','');
	$new_state = array('','','');
	$new_contestant_championships = array(0,0,0);
	$new_contestant_prior_winnings = array(0,0,0);
	$new_contestant_initial_skill_level = array(0,0,0);
	$new_contestant_level = array(0,0,0);
	
	$max_championships = $contestant_championships[0];
	$med_championships = $contestant_championships[0];
	$min_championships = $contestant_championships[0];
	*/
	#$new_order = array(0,1,2);
	
	/*
	for ($a = 1; $a <= 2; $a++)
	{
		if ($contestant_championships[$a] > $max_championships)
		{
			$min_championships = $med_championships;
			$med_championships = $max_championships;
			$max_championships = $contestant_championships[$a];
			$move_along = array_shift($new_order);
			array_push($new_order, $a);
			//$new_order[0] = $new_order[1];
			//$new_order[1] = $new_order[2];
			//$new_order[2] = $a;
		}
		else if ($contestant_championships[$a] < $min_championships)
		{
			$max_championships = $med_championships;
			$med_championships = $min_championships;
			$min_championships = $contesant_championships[$a];
			array_unshift($new_order, $a);
			array_pop($new_order);
		}
		else
		{
			$med_championships = $contesant_championships[$a];
			$new_order[1] = $a;
		}
	}
	echo ('Max Championships:'.$max_championships.'<br>');
	echo ('Med Championships:'.$med_championships.'<br>');
	echo ('Min Championships:'.$min_championships.'<br>');
	echo ('Order:'.$new_order[0].','.$new_order[1].','.$new_order[2]);
	
	/*
	for ($a = 0; $a <= 2; $a++)
	{
		if ($contestant_championships[$new_positions[$a]] > 0)
		{
			$new_id[$a] = $contestant_id[$new_order[$a]];
			$new_contestant_championships[$a] = $contestant_championships[$new_order[$a]];
			$new_contestant_prior_winnings[$a] = $contestant_winnings[$new_order[$a]];
			$new_contestant_level[$a] = $contestant_level[$new_order[$a]];
		}
	}
	*/
	//      0 0 1
	//  now 1 0 0
	//  seating...
	//      0 0 0
	//      0 0 0
	//      0 0 1
	
	//Set variables for next game.
	//$contestant_championships = array(0,0,0);
	//$contestant_prior_winnings = array(0,0,0);
	//$contestant_level = array(1,1,1);

	//Seat new challengers.
	/*
	if ($challengers > 0)
	{
		for ($a = 0; $a <= $challengers - 1; $a++)
		{
			$player_row = mysqli_fetch_array($player_result);
			$contestant_id[$a] = $row['id'];
			$contestant_fname[$a] = $row['fname'];
			$contestant_lname[$a] = $row['lname'];
			$contestant_occupation[$a] = $row['occupation'];
			$contestant_city[$a] = $row['city'];
			$contestant_state[$a] = $row['state'];
			$contestant_initial_skill_level[$a] = $row['init_skill_level'];
		}		
	}
	
	//Seat the champion or champions.
	for ($a = $challengers; $a <= 2; $a++)
	{
		$contestant_id[$a] = $new_id[$a];
		$contestant_fname[$a] = $new_fname[$a];
		$contestant_lname[$a] = $new_lname[$a];
		$contestant_occupation[$a] = $new_occupation[$a];
		$contestant_city[$a] = $new_city[$a];
		$contestant_state[$a] = $new_state[$a];
		$contestant_championships[$a] = $new_contestant_championships[$a];
		$contestant_prior_winnings[$a] = $new_contestant_prior_winnings[$a];
		$contestant_initial_skill_level[$a] = $new_contestant_initial_skill_level[$a];
		$contestant_level[$a] = $new_contestant_level[$a];
	}
	*/
	$game_script = array('','','','');

	#echo ('About to generate game skill levels for next game.<br>');
	#$contestant_game_skill_level = array(rand(1,6),rand(1,6),rand(1,6));
	
	#//From https://stackoverflow.com/questions/28807774/php-add-one-week-to-a-user-defined-date
	#$start_date = $current_air_date;
	#$date = strtotime($start_date);
	#$date = strtotime("+1 week", $date);
	#$current_air_date = strval($date);

	//Generate random game skill level values for the next game.

	//Generate data stream for next game.
	#echo ('About to generate data stream for next game.<br>');
	#$data_stream = "";
	#for ($a = 1; $a <= 250; $a++)
	#{
#		$data_stream = $data_stream . strval(rand(1,6));
	#}
	#echo ('Data stream is: '.$data_stream.'<br>');

	//echo ('<br>Starting next game.<br>');

	
	
// End of 100 game loop.
}

	
//echo '<br><br><br>Timestamp: '.$data_stream_timestamp.'<br>Simulated Dice Rolls (courtesy of <a href="http://www.random.org" target="new">RANDOM.ORG</a>): '.$data_stream.'<br>';


?>
</article>
<footer id="myFooter"></footer>
<script src="elements.js"></script>
<!--</div>-->
</div>
</body>
</html>


<?php
	function getNextNumber()
	{
		global $data_stream,$data_stream_value, $data_stream_counter;
		$data_stream_counter++;
		//echo substr($data_stream,$data_stream_counter,1);
		return substr($data_stream,$data_stream_counter,1);
		
	}
?>


<?php
	function getNextContestant()
	{
		global $contestant_counter;
		$contestant_counter++;
		return $contestant_counter;
	}
?>

<?php
	function displayReboundTable()
	{
		global $contestant_fname, $rebound_score;
		
		//echo '<table border="1"><tr><td><b>Player</b></td><td><b>Score</b></td></tr>';
			for ($a = 0; $a <= 2; $a++)
			{
				//echo '<tr><td>'.$contestant_fname[$a].'</td><td>'.$rebound_score[$a].'</td></tr>';
			}
			//echo '</table><br>';
	}

?>

<?php
	function clearAllGames()
	{
		$result = mysqli_query($db, "TRUNCATE TABLE `sdevelop_youtube`.`TSQ100 Games`;") or die ('Error truncating table..');	
		$result = mysqli_query($db, "ALTER TABLE `sdevelop_youtube`.`TSQ100 Games` AUTO_INCREMENT = 1;") or die ('Error altering table.');
	}

?>


