
<html>
<head>
<title>The Saturday Quiz Sim</title>
<link rel='stylesheet' href='style.css' id='styler'>

</head>
<body>
<div class="container">
<div id="nocustom">
<header id="myHeader"></header>
<nav id="navBar">



</nav>
<article>
<br>
<br>
<b>DISCLAIMERS: </b>
<ul>
<li>I did borrow a little styling from the <a href="http://www.j-archive.com" target="new">J-Archive</a>.</li>	
<li>The contestant names you see were randomly generated by <a href="http://www.fakenamegenerator.com/" target="new">Fake Name Generator</a>.  Any relation to any persons, living or dead, are entirely coincidental, especially with Show #1; that was just a lucky roll of the virtual dice!</li>
<li><b><u>NO REAL MONEY NOR PRIZES ARE AWARDED.</u></b>  This is just a simulation.</li>
<li>There is no trademark for The Saturday Quiz.  If anyone legally owns the name The Saturday Quiz, please <a href="mailto:tsd@thesweepingdeveloper.com">e-mail me</a> to request removal.</li>
</ul>
<?php
//This is just the login, and not the constants file.  Obviously, this is something that needs refactoring, among other things.
include 'mysql_login.php';


$season_words = ['One','Two','Three','Four'];

for ($s = 1; $s <= 2; $s++)
{
	echo ('<h1><p align="center"><b>Season '.$season_words[$s-1].' Top Nine Champions</b></p></h1>');
	echo ('<table border="1" align="center">');
	$contestant_data = [];
	$contestant_list = [];
	$contestant_duplicates = [];
	$final_list_data = [];


	$query = "SELECT `Contestants`.`fname`, `Contestants`.`lname`, `Games`.`c3_id`, `Games`.`c3_championships`, `Games`.`c3_level`, `Games`.`c3_winnings` 
			  FROM sdevelop_youtube.`TSQ Games` AS `Games`, sdevelop_youtube.`TSQ Contestants` AS `Contestants` 
			  WHERE `season` = ". $s ." AND `Games`.`mode` = 0 AND `c3_id` = `Contestants`.`id` 
			  ORDER BY `c3_championships` DESC, `c3_level` DESC, `c3_winnings` DESC;";
	$result = mysqli_query($db, $query) or die ('Error querying game data for Contestant #3.');

	while ($row = mysqli_fetch_array($result))
	{
		array_push($contestant_data, $row);
	}

	$query = "SELECT `Contestants`.`fname`, `Contestants`.`lname`, `Games`.`c2_id`, `Games`.`c2_championships`, `Games`.`c2_level`, `Games`.`c2_winnings` 
			  FROM sdevelop_youtube.`TSQ Games` AS `Games`, sdevelop_youtube.`TSQ Contestants` AS `Contestants` 
			  WHERE `season` = ". $s ." AND `Games`.`mode` = 0 AND `c2_id` = `Contestants`.`id` 
			  ORDER BY `c2_championships` DESC, `c2_level` DESC, `c2_winnings` DESC;";
	$result = mysqli_query($db, $query) or die ('Error querying game data for Contestant #2.');

	while ($row = mysqli_fetch_array($result))
	{
		array_push($contestant_data, $row);
	}

	$query = "SELECT `Contestants`.`fname`, `Contestants`.`lname`, `Games`.`c1_id`, `Games`.`c1_championships`, `Games`.`c1_level`, `Games`.`c1_winnings` 
			  FROM sdevelop_youtube.`TSQ Games` AS `Games`, sdevelop_youtube.`TSQ Contestants` AS `Contestants` 
			  WHERE `season` = ". $s ." AND `Games`.`mode` = 0 AND `c1_id` = `Contestants`.`id` 
			  ORDER BY `c1_championships` DESC, `c1_level` DESC, `c1_winnings` DESC;";
	$result = mysqli_query($db, $query) or die ('Error querying game data for Contestant #1.');

	while ($row = mysqli_fetch_array($result))
	{
		array_push($contestant_data, $row);
	}
	$num_of_entries = sizeof($contestant_data) / 3;
	for ($a = 0; $a <= 2; $a++)
	{
		
		#echo ("Contestant Position #".(3-$a).":\n");
		for ($b = 0; $b <= $num_of_entries - 1; $b++)
		{
			$index = $a * $num_of_entries + $b;
			#echo ($contestant_data[$index][2]);
			if (in_array($contestant_data[$index][2], $contestant_list) and in_array($contestant_data[$index][2], $contestant_duplicates) == false)
			{
				array_push($contestant_duplicates, $contestant_data[$index][2]);
			}
			else if (in_array($contestant_data[$index][2], $contestant_list) == false and in_array($contestant_data[$index][2], $contestant_duplicates) == false)
			{
				array_push($contestant_list, $contestant_data[$index][2]);
				array_push($final_list_data, $contestant_data[$index]);
			}
			
		}
		echo ("\n");
	}

	#echo ("Contestant Duplicate IDs:\n");
	#for ($a = 0; $a <= sizeof($contestant_duplicates); $a++)
	#{
	#	echo ($contestant_duplicates[$a]."\n");
	#}
	#echo ("\nContestant List:\n");

	echo ('<tr>
			<th>Rank</th>
			<th>Player Name</th>
			<th>Championships</th>
			<th>Level Reached</th>
			<th>"Winnings"</th>
		  </tr>');
		  
	for ($a = 1; $a <= 9; $a++)
	{
		$f_name = $final_list_data[$a-1][0];
		$l_name = $final_list_data[$a-1][1];
		$championships = $final_list_data[$a-1][3];
		$level_reached = $final_list_data[$a-1][4];
		$winnings = $final_list_data[$a-1][5];
		echo ('<tr>
			   <td>'. $a .'</td>
			   <td>'. $f_name.' '.$l_name.'</td>
			   <td>'. $championships .'</td>
			   <td>'. $level_reached .'</td>
			   <td>$'. number_format($winnings) .'</td></tr>');
		
		#echo($final_list_data[$a][0]."\n");
	}

	echo ('</table>');



	
}

?>



<br>

<?php

	for ($a = 1; $a <= 20; $a++)
	{
		echo '<br>';
	}

?>

</article>
<footer id="myFooter"></footer>
<script src="elements.js"></script>
</div>
</div>
</body>
</html>

